import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const packageRoot = fileURLToPath(new URL("../", import.meta.url));
const schemaPath = new URL("../schema/site-manifest.schema.json", import.meta.url);
const outputPath = new URL("../src/generated/site-manifest.ts", import.meta.url);
const runtimeSchemaPath = new URL("../src/generated/schema.ts", import.meta.url);

const schema = JSON.parse(await readFile(schemaPath, "utf8"));

function resolve(node) {
  if (!node.$ref) {
    return node;
  }
  const prefix = "#/$defs/";
  if (!node.$ref.startsWith(prefix)) {
    throw new Error(`Unsupported schema reference: ${node.$ref}`);
  }
  const name = node.$ref.slice(prefix.length);
  const resolved = schema.$defs?.[name];
  if (!resolved) {
    throw new Error(`Missing schema definition: ${name}`);
  }
  return resolved;
}

function propertyName(name) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
    ? name
    : JSON.stringify(name);
}

function toType(node, indent = 0) {
  const resolved = resolve(node);
  if (Object.hasOwn(resolved, "const")) {
    return JSON.stringify(resolved.const);
  }
  if (resolved.type === "string") {
    return "string";
  }
  if (resolved.type === "integer" || resolved.type === "number") {
    return "number";
  }
  if (resolved.type === "boolean") {
    return "boolean";
  }
  if (resolved.type === "array") {
    return `ReadonlyArray<${toType(resolved.items, indent)}>`;
  }
  if (resolved.type === "object") {
    const required = new Set(resolved.required ?? []);
    const padding = " ".repeat(indent);
    const childPadding = " ".repeat(indent + 2);
    const properties = Object.entries(resolved.properties ?? {}).map(
      ([name, property]) =>
        `${childPadding}readonly ${propertyName(name)}${
          required.has(name) ? "" : "?"
        }: ${toType(property, indent + 2)};`,
    );
    return `Readonly<{\n${properties.join("\n")}\n${padding}}>`;
  }
  throw new Error(`Unsupported schema type at ${JSON.stringify(resolved)}`);
}

const generated = `/**
 * This file is generated from schema/site-manifest.schema.json.
 * Do not edit this file directly.
 */

export type SiteManifest = ${toType(schema)};

export type CapabilityName =
  SiteManifest["compatibility"]["required_capabilities"][number];
`;
const generatedRuntimeSchema = `/**
 * This file is generated from schema/site-manifest.schema.json.
 * Do not edit this file directly.
 */

export const siteManifestSchema = ${JSON.stringify(schema, null, 2)} as const;
`;

const mode = process.argv[2];
if (mode === "--write") {
  await writeFile(outputPath, generated, "utf8");
  await writeFile(runtimeSchemaPath, generatedRuntimeSchema, "utf8");
  process.stdout.write(`generated ${outputPath.pathname}\n`);
} else if (mode === "--check") {
  const current = await readFile(outputPath, "utf8");
  const currentRuntimeSchema = await readFile(runtimeSchemaPath, "utf8");
  if (current !== generated || currentRuntimeSchema !== generatedRuntimeSchema) {
    throw new Error(
      `Generated Site Manifest type is stale. Run pnpm --dir ${packageRoot} generate.`,
    );
  }
  process.stdout.write("Site Manifest generated type is current\n");
} else {
  throw new Error("Expected --write or --check");
}
