<?php

return [
    'templates' => [
        'email_verification' => '認証リンク送信時',
        'registration_completed' => '認証成功登録時',
        'coin_purchase_completed' => 'コイン購入完了時',
        'shipping_requested' => '発送依頼時',
        'shipping_completed' => '発送完了時',
        'user_closed' => '退会時',
        'contact_received' => 'お問い合わせ完了時',
        'password_reset' => 'パスワード再設定時',
        'email_change_verification' => 'メールアドレス変更認証時',
        'email_change_completed' => 'メールアドレス変更完了時',
        'password_changed' => 'パスワード変更完了時',
    ],
    'variables' => [
        'user_name' => 'ユーザー名',
        'full_name' => '氏名',
        'address' => '住所',
        'phone_number' => '電話番号',
        'gacha_names' => 'ガチャ名',
        'prize_names' => '景品名',
        'purchase_plan' => 'コイン購入プラン',
        'purchase_amount' => '購入金額',
        'verification_url' => '認証リンク',
        'reset_url' => 'パスワード再設定リンク',
        'email_change_verification_url' => 'メールアドレス変更認証リンク',
        'expires_in_minutes' => '有効期限（分）',
        'contact_body' => 'お問い合わせ内容',
    ],
    'preview_values' => [
        'user_name' => 'サンプルユーザー',
        'full_name' => '山田 太郎',
        'address' => '〒100-0001 東京都千代田区千代田1-1 サンプルビル101',
        'phone_number' => '090-1234-5678',
        'gacha_names' => ['春のガチャ', '夏のガチャ'],
        'prize_names' => ['景品A', '景品B', '景品C'],
        'purchase_plan' => 'サンプルコインプラン',
        'purchase_amount' => '1,000円',
        'verification_url' => 'https://example.test/verify/sample',
        'reset_url' => 'https://example.test/reset-password/sample',
        'email_change_verification_url' => 'https://example.test/change-email/sample',
        'expires_in_minutes' => '60',
        'contact_body' => 'サンプルのお問い合わせ内容です。',
    ],
];
