ServerName platform-api.local

<VirtualHost *:8000>
    ServerName platform-api.local
    DocumentRoot /var/www/backend/public

    <Directory /var/www/backend/public>
        AllowOverride All
        DirectoryIndex index.php
        FallbackResource /index.php
        Options FollowSymLinks
        Require all granted
    </Directory>

    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
